on:
  release:
    types: [published]

name: Neuroconductor release

permissions:
  contents: write

jobs:
  neuroconductor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Trigger Neuroconductor update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "neuroc_release ${{ github.event.release.tag_name }} [skip ci]"
          git push
